name: hydracoach
description: "Smart hydration tracking with electrolyte balance"
publish_to: 'none'

# Версия приложения: 2.1.4 (Critical updates: Firebase 4.x-6.x + Code quality) + номер сборки 35
version: 2.1.4+35 # версия+номер_сборки

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  # 🌍 ЛОКАЛИЗАЦИЯ
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # UI и иконки
  cupertino_icons: ^1.0.8
  
  # Стейт менеджмент
  provider: ^6.1.5+1
  
  # Локальное хранение
  shared_preferences: ^2.5.3
  
  # Утилиты
  http: ^1.5.0
  timezone: ^0.10.0
  # flutter_timezone удален - используем ручное определение таймзоны
  
  # UI компоненты
  fl_chart: ^1.0.0
  flutter_animate: ^4.5.2
  carousel_slider: ^5.0.0
  
  # Разрешения и уведомления
  flutter_local_notifications: ^19.4.1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1

  # 🔥 FIREBASE - основные сервисы
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_analytics: ^12.0.2
  firebase_remote_config: ^6.0.2
  firebase_crashlytics: ^5.0.2

  # 📁 ФАЙЛЫ - экспорт данных
  path_provider: ^2.1.5
  csv: ^6.0.0
  simple_animations: ^5.2.0

  # GDPR/Privacy compliance
  usercentrics_sdk: ^2.23.0

  # 📊 ATTRIBUTION & MONETIZATION
  appsflyer_sdk: ^6.17.5
  applovin_max: ^4.5.2

  # 💰 IN-APP PURCHASES
  in_app_purchase: ^3.2.0

  # 🔗 URL LAUNCHER
  url_launcher: ^6.3.0

  # 📝 LOGGING
  logger: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # 🎨 Для генерации иконок
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  # 🌍 ГЕНЕРАЦИЯ ЛОКАЛИЗАЦИИ
  generate: true
  
  # 🎨 Assets и иконки
  assets:
    - assets/images/
    - assets/notifications/
  
  # Шрифты (если будем добавлять кастомные)
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: fonts/Montserrat-Regular.ttf
  #       - asset: fonts/Montserrat-Bold.ttf
  #         weight: 700

# 🎨 КОНФИГУРАЦИЯ ИКОНОК
flutter_launcher_icons:
  android: "ic_launcher"  # Важно: используем ic_launcher, не launcher_icon
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  
  # Адаптивная иконка для Android
  adaptive_icon_background: "#00D4DB"  # Бирюзовый фон
  adaptive_icon_foreground: "assets/images/app_icon.png"  # Пока та же капля, нужно будет заменить на белую
  
  # iOS настройки
  remove_alpha_ios: true